# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xnA0CJyeL8mfrreYHEimZxvOnF8FN4_K

**Task 07: Querying RDF(s)**
"""

# !pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
# Visualize the results
result = [] #list of tuples

for c in g.subjects(RDF.type, RDFS.Class):
    superclass = None
    for sc in g.objects(c, RDFS.subClassOf):
        superclass = sc
    result.append((c, superclass))

for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query = """
SELECT ?c ?sc
WHERE {
  ?c rdf:type rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

classes_to_check = {ns.Person}
checked = set()

while classes_to_check:
    current_class = classes_to_check.pop()
    checked.add(current_class)

    for sub in g.subjects(RDFS.subClassOf, current_class):
        if sub not in checked:
            classes_to_check.add(sub)

    for ind in g.subjects(RDF.type, current_class):
        if ind not in individuals:
            individuals.append(ind)

# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

from rdflib.plugins.sparql import prepareQuery

query = prepareQuery("""
SELECT DISTINCT ?ind
WHERE {
  ?ind rdf:type ?cls .
  ?cls rdfs:subClassOf* ns:Person .
}
""",
initNs={"rdf": RDF, "rdfs": RDFS, "ns": ns}
)

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = prepareQuery("""
SELECT DISTINCT ?name ?type
WHERE {
  ?ind rdf:type ?type .
  ?ind ns:knows ns:Rocky .
  {
    ?ind ns:hasName ?name .
  } UNION {
    ?ind rdfs:label ?name .
  }
}
""",
initNs={"rdf": RDF, "rdfs": RDFS, "ns": ns}
)

# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = prepareQuery("""
SELECT DISTINCT ?name
WHERE {
  ?person rdfs:label ?name .
  ?person ns:hasColleague ?colleague .

  {
    # colega directo tiene una mascota
    ?colleague ns:ownsPet ?pet .
  }
  UNION
  {
    # colega de un colega tiene una mascota
    ?colleague ns:hasColleague ?colleague2 .
    ?colleague2 ns:ownsPet ?pet .
  }
}
""",
initNs={"rdfs": RDFS, "ns": ns}
)

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")