# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO

result = [] #list of tuples
classes = set(g.subjects(RDF.type, RDFS.Class))
for c in classes:
    supers = list(g.objects(c, RDFS.subClassOf))
    if supers:
        for s in supers:
            result.append((c, s))
    else:
        result.append((c, None))

for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?c ?sc
WHERE {
  ?c rdf:type rdfs:Class .
  OPTIONAL {
    ?c rdfs:subClassOf ?sc .
    FILTER(?c != ?sc)
  }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

def get_all_subclasses(class_uri, graph):
    subclasses = set()
    for subclass in graph.subjects(RDFS.subClassOf, class_uri):
        subclasses.add(subclass)
        # Llamada recursiva para sub-subclases
        subclasses.update(get_all_subclasses(subclass, graph))
    return subclasses

all_classes = {ns.Person} | get_all_subclasses(ns.Person,g)

for c in all_classes:
    for ind in g.subjects(RDF.type, c):
        individuals.append(ind)
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns: <http://oeg.fi.upm.es/def/people#>

SELECT ?ind
WHERE {
  ?ind rdf:type/rdfs:subClassOf* ns:Person .
}
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query =  """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ns: <http://oeg.fi.upm.es/def/people#>

SELECT ?name ?type
WHERE {
  ?person ns:knows ns:Rocky .
  ?person rdfs:label ?name .
  ?person rdf:type ?type .
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query =  """SELECT DISTINCT ?name
WHERE {
  {
    ?x <http://oeg.fi.upm.es/def/people#hasColleague> ?y .
    ?y <http://oeg.fi.upm.es/def/people#ownsPet> ?pet .
    ?pet rdf:type <http://oeg.fi.upm.es/def/people#Animal> .
  }
  UNION
  {
    ?x <http://oeg.fi.upm.es/def/people#hasColleague> ?y .
    ?y <http://oeg.fi.upm.es/def/people#hasColleague> ?z .
    ?z <http://oeg.fi.upm.es/def/people#ownsPet> ?pet .
    ?pet rdf:type <http://oeg.fi.upm.es/def/people#Animal> .
  }
  ?x <http://www.w3.org/2000/01/rdf-schema#label> ?name .
}"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")