# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/a-skyy/Curso2025-2026/blob/master/Assignment4/course_materials/notebooks/Task06.ipynb

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
from rdflib import Graph, Namespace, Literal, URIRef, XSD
from rdflib.namespace import RDF, RDFS

# Crear el grafo
g = Graph()

# Namespaces
ontology     = Namespace("http://oeg.fi.upm.es/def/people#")
person       = Namespace("http://oeg.fi.upm.es/resource/person/")
organization = Namespace("http://oeg.fi.upm.es/resource/organization/")

# Asociar los prefijos al grafo
g.namespace_manager.bind("ontology", ontology, override=True)
g.namespace_manager.bind("person", person, override=True)
g.namespace_manager.bind("organization", organization, override=True)
g.namespace_manager.bind("rdf", RDF)
g.namespace_manager.bind("rdfs", RDFS)
g.namespace_manager.bind("xsd", XSD)

# Raúl García Castro
g.add((person.Raul, ontology.hasFullName, Literal("Raúl García Castro")))
g.add((person.Raul, ontology.hasBirthDate, Literal("1975-12-26", datatype=XSD.date)))
g.add((person.Raul, ontology.isMemberOf, organization.OEG))
g.add((person.Raul, ontology.hasWebPage, URIRef("http://oeg.fi.upm.es/")))
# Visualización del grafo resultante
print("=== Task 6.0 Namespaces & Example ===")
ttl = g.serialize(format="turtle")
print(ttl.decode() if isinstance(ttl, (bytes, bytearray)) else ttl)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

for cls, parent in [
    ("Person", None),
    ("Professor", "Person"),
    ("AssociateProfessor", "Professor"),
    ("FullProfessor", "Professor"),
    ("InterimAssociateProfessor", "AssociateProfessor"),
]:
    c = ontology[cls]
    g.add((c, RDF.type, RDFS.Class))
    g.add((c, RDFS.label, Literal(cls, datatype=XSD.string)))
    if parent:
        g.add((c, RDFS.subClassOf, ontology[parent]))

for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

for prop, label, domain, range_ in [
    (ontology.hasColleague, "hasColleague", ontology.Person, ontology.Person),
    (ontology.hasName,      "hasName",      ontology.Person, RDFS.Literal),
    (ontology.hasHomePage,  "hasHomePage",  ontology.FullProfessor, RDFS.Literal),
]:
    g.add((prop, RDF.type, RDF.Property))
    g.add((prop, RDFS.label,  Literal(label, datatype=XSD.string)))
    g.add((prop, RDFS.domain, domain))
    g.add((prop, RDFS.range,  range_))
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

for ind in (person.Oscar, person.Asun, person.Raul):
    g.remove((ind, None, None))

# person:Oscar
g.add((person.Oscar, RDF.type, ontology.AssociateProfessor))
g.add((person.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((person.Oscar, ontology.hasName, Literal("Óscar Corcho García", datatype=XSD.string)))
g.add((person.Oscar, ontology.hasColleague, person.Asun))

# person:Asun
g.add((person.Asun, RDF.type, ontology.FullProfessor))
g.add((person.Asun, RDFS.label, Literal("Asun", datatype=XSD.string)))
g.add((person.Asun, ontology.hasHomePage, Literal("http://oeg.fi.upm.es/", datatype=XSD.string)))
g.add((person.Asun, ontology.hasColleague, person.Raul))

# person:Raul
g.add((person.Raul, RDF.type, ontology.InterimAssociateProfessor))
g.add((person.Raul, RDFS.label, Literal("Raul", datatype=XSD.string)))
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

foaf  = Namespace("http://xmlns.com/foaf/0.1/")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")
example4 = Namespace("http://www.semanticweb.org/ontologies/example4.rdf#")

# Asociar prefijos
g.namespace_manager.bind("foaf", foaf)
g.namespace_manager.bind("vcard-rdf", vcard)
g.namespace_manager.bind("example4", example4)

# Añadir información de contacto
g.add((person.Oscar, RDF.type, example4.Person))
g.add((person.Oscar, foaf.email, Literal("oscar@example.com", datatype=XSD.string)))
g.add((person.Oscar, vcard.Given, Literal("Oscar", datatype=XSD.string)))
g.add((person.Oscar, vcard.Family, Literal("Corcho", datatype=XSD.string)))
g.add((person.Oscar, vcard.FN, Literal("Óscar Corcho García", datatype=XSD.string)))
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")