@prefix ns: <http://bcn-mobility-air.org/ontology/> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix geo: <http://www.w3.org/2003/01/geo/wgs84_pos#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

# --------------------------------------------------------------------------
# CONSULTAS DE VALIDACIÓN: Enfocadas en el enriquecimiento de ns:RoadSegment
# --------------------------------------------------------------------------

# 1. Contar RoadSegments que SI tienen nombre
SELECT (COUNT(DISTINCT ?s) AS ?count)
WHERE { 
    ?s a ns:RoadSegment ;
       ns:name ?name . 
}

;

# 2. Contar RoadSegments que NO tienen nombre (Debe ser 0)
SELECT (COUNT(DISTINCT ?s) AS ?count)
WHERE {
    ?s a ns:RoadSegment .
    FILTER NOT EXISTS { ?s ns:name ?name . }
}

;

# 3. Muestra de RoadSegments con todos sus atributos (Nombre, Inicio, Fin)
SELECT ?segment ?name ?start ?end
WHERE {
  ?segment a ns:RoadSegment ;
           ns:name ?name ;
           ns:startPoint ?start ;
           ns:endPoint ?end .
}
LIMIT 5

;

# 4. Distribución de nombres (Confirmar que ns:RoadSegment aparece)
SELECT ?class (COUNT(DISTINCT ?s) AS ?count)
WHERE {
  ?s a ?class ;
     ns:name ?name .
}
GROUP BY ?class
ORDER BY DESC(?count)

;

# 5. Comprobar legibilidad del nombre (Buscando "Diagonal")
SELECT ?s ?name ?start
WHERE {
  ?s a ns:RoadSegment ;
     ns:name ?name ;
     ns:startPoint ?start .
  FILTER(CONTAINS(LCASE(STR(?name)), "diagonal"))
}
LIMIT 5

;

# --------------------------------------------------------------------------
# CONSULTAS DE APLICACIÓN
# --------------------------------------------------------------------------

# Q1: ¿Cuáles son los tramos en "Diagonal" con la MEJOR CONGESTION?
SELECT DISTINCT ?segment ?name ?start ?end ?congestion 
WHERE { 
    ?segment a ns:RoadSegment ;
             ns:name ?name ;
             ns:startPoint ?start ;
             ns:endPoint ?end ;
             ns:hasCongestionMeasurement/ns:congestionLevel ?congestion .
    
    FILTER(CONTAINS(LCASE(STR(?name)), "diagonal"))
    FILTER(?congestion = "Optimum"^^xsd:string)
    
}
LIMIT 10

;

# Q2: ¿Cuál es la MEJOR CALIDAD DE AIRE en un tramo de "Diagonal"?
SELECT DISTINCT ?streetName ?startPoint ?stationName ?aqValue
WHERE {
    ?segment a ns:RoadSegment ;
             ns:name ?streetName ;
             ns:startPoint ?startPoint ;
             ns:hasLocation ?roadLocation .
    FILTER(CONTAINS(LCASE(STR(?streetName)), "diagonal"))

    ?station a ns:AirQualityStation ;
             ns:name ?stationName ;
             ns:hasLocation ?stationLocation .
    
    ?station ns:hasAirQualityReading ?reading .
    
    ?reading ns:measuresPollutant [ns:name "nitric oxide"] ; # Sin ^^xsd:string
             ns:value ?aqValue .
}
ORDER BY ASC(?aqValue) 
LIMIT 10