# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

#pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# TO DO
from rdflib import RDF, RDFS
result = [] #list of tuples
# Recorremos todas las clases del grafo
for cls in g.subjects(RDF.type, RDFS.Class):
    # Buscamos si tiene una superclase (rdfs:subClassOf)
    superclass = g.value(subject=cls, predicate=RDFS.subClassOf)
    # Si no tiene, devolvemos None
    if superclass is None:
        result.append((cls, None))
    else:
        result.append((cls, superclass))
# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """
    SELECT ?c ?sc
    WHERE {
      ?c rdf:type rdfs:Class .
      OPTIONAL { ?c rdfs:subClassOf ?sc . }
    } 
    """

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# Diccionario que mapea cada clase a sus individuos
class_to_individuals = {}
for cls in g.subjects(RDF.type, RDFS.Class):
    class_to_individuals[cls] = list(g.subjects(RDF.type, cls))

# Función recursiva para obtener individuos de Person y sus subclases
def get_individuals(cls):
    inds = set(class_to_individuals.get(cls, []))
    for subcls in g.subjects(RDFS.subClassOf, cls):
        inds.update(get_individuals(subcls))
    return inds

# Lista final de individuos
individuals = list(get_individuals(ns.Person))
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query = """
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX peo: <http://oeg.fi.upm.es/def/people#>

SELECT DISTINCT ?ind
WHERE {
    ?cls rdfs:subClassOf* peo:Person .
    ?ind rdf:type ?cls .
}
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = """
PREFIX peo: <http://oeg.fi.upm.es/def/people#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


SELECT ?name ?type
WHERE {
    ?person peo:knows peo:Rocky .
    ?person rdf:type ?type .
    {
      ?person peo:hasName ?name .
    }
    UNION
    {
      ?person rdfs:label ?name .
    }
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
PREFIX peo:  <http://oeg.fi.upm.es/def/people#>
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?name
WHERE {
  {
    ?s peo:hasColleague/peo:ownsPet ?pet .
    ?pet rdf:type peo:Animal .
  }
  UNION
  {
    ?s peo:hasColleague/peo:hasColleague/peo:ownsPet ?pet2 .
    ?pet2 rdf:type peo:Animal .
  }
  ?s rdfs:label ?name .
}
ORDER BY ?name
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")