################################################################################
# PREFIXES
################################################################################
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

################################################################################
# QUERY 9 - First ten parkings linked to Wikidata
## Retrieves the first ten parkings that have been linked to Wikidata entities via owl:sameAs
## Results are ordered by the parking identifier (dcterms:identifier)
################################################################################
SELECT DISTINCT ?id ?name ?wikidata
WHERE {
  ?p a schema:ParkingFacility ;
     dcterms:identifier ?id ;
     schema:name ?name ;
     owl:sameAs ?wikidata .
  FILTER(STRSTARTS(STR(?wikidata), "https://www.wikidata.org/entity/"))
}
ORDER BY ASC(xsd:integer(?id))
LIMIT 10

################################################################################
# QUERY 10 - First ten parkings with linked municipalities in Wikidata
## Retrieves the first ten parkings with their linked municipalities in Wikidata
## Results are ordered by the parking identifier (dcterms:identifier)
################################################################################
SELECT DISTINCT ?id ?name ?city ?wikidataCity
WHERE {
  ?p a schema:ParkingFacility ;
     dcterms:identifier ?id ;
     schema:name ?name ;
     schema:address ?pAddr .
  ?pAddr schema:addressLocality ?city .
  ?city owl:sameAs ?wikidataCity .
  FILTER(STRSTARTS(STR(?wikidataCity), "https://www.wikidata.org/entity/"))
}
ORDER BY ASC(xsd:integer(?id))
LIMIT 10
