# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="turtle")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

result = []
for cl in g.subjects(RDF.type, RDFS.Class):
    superclass = None
    for supercl in g.objects(cl, RDFS.subClassOf):
      superclass = supercl
    result.append((cl, superclass))
# Visualize the results
for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)


"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query =  """SELECT DISTINCT ?c ?sc
WHERE {
  ?c rdf:type rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
} """
for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""
ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = [] 

classes = set([ns.Person])
added = True
while added:
    added = False
    for cls in list(classes):
        for sub in g.subjects(RDFS.subClassOf, cls):
            if sub not in classes:
                classes.add(sub)
                added = True

# Collect individuals typed with any of those classes
for cls in classes:
    for ind in g.subjects(RDF.type, cls):
        if ind not in individuals:
            individuals.append(ind)
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?ind WHERE {
  ?class rdfs:subClassOf* ns:Person .
  ?ind rdf:type ?class .
}
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)
"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query =  """
PREFIX ppl:  <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?name ?type WHERE {
  ?person ppl:knows ppl:Rocky .
  ?person rdfs:label ?name .
  ?person rdf:type ?type .
}
"""
# TO DO
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)


"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query =  """
PREFIX ppl:   <http://oeg.fi.upm.es/def/people#>
SELECT DISTINCT ?name WHERE {
  {
    ?p ppl:hasColleague ?c .
    ?c ppl:ownsPet ?pet .
    ?p rdfs:label ?name .
  } UNION {
    ?p ppl:hasColleague ?c1 .
    ?c1 ppl:hasColleague ?c2 .
    ?c2 ppl:ownsPet ?pet .
    ?p rdfs:label ?name .
  }
}
"""

for r in g.query(query):
  print(r.name)

# TO DO
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")
