# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/vilf0106/Curso2025-2026/blob/master/Assignment4/course_materials/notebooks/Task06.ipynb

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
# === Task 6.0 ===
ontology = Namespace("http://oeg.fi.upm.es/def/people#")
person   = Namespace("http://oeg.fi.upm.es/resource/person/")

g.namespace_manager.bind("ontology", ontology, override=False)
g.namespace_manager.bind("person",   person,   override=False)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO
pairs = [
    ("Person",                    None),
    ("Professor",                 "Person"),
    ("AssociateProfessor",        "Professor"),
    ("FullProfessor",             "Professor"),
    ("InterimAssociateProfessor", "AssociateProfessor"),
]

for cls, parent in pairs:
    c = ontology[cls]
    g.add((c, RDF.type, RDFS.Class))
    g.add((c, RDFS.label, Literal(cls, datatype=XSD.string)))
    if parent:
        g.add((c, RDFS.subClassOf, ontology[parent]))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO

from rdflib import Namespace, Literal
from rdflib.namespace import RDF, RDFS, XSD



triples = [
    (ontology.hasColleague, "hasColleague", ontology.Person,           ontology.Person),
    (ontology.hasName,      "hasName",      ontology.Person,           RDFS.Literal),
    (ontology.hasHomePage,  "hasHomePage",  ontology.FullProfessor,    RDFS.Literal),
]

for prop, label, domain, rng in triples:
    g.add((prop, RDF.type, RDF.Property))
    g.add((prop, RDFS.label,  Literal(label, datatype=XSD.string)))
    g.add((prop, RDFS.domain, domain))
    g.add((prop, RDFS.range,  rng))


for s, p, o in g:
    print(s, p, o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO

from rdflib import Namespace, Literal
from rdflib.namespace import RDF, RDFS, XSD




g.add((person.Oscar, RDF.type, ontology.Person))
g.add((person.Asun,  RDF.type, ontology.FullProfessor))
g.add((person.Raul,  RDF.type, ontology.InterimAssociateProfessor))

g.add((person.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))
g.add((person.Asun,  RDFS.label, Literal("Asun",  datatype=XSD.string)))
g.add((person.Raul,  RDFS.label, Literal("Raul",  datatype=XSD.string)))


g.add((person.Oscar, ontology.hasName,     Literal("Óscar Corcho García", datatype=XSD.string)))
g.add((person.Asun,  ontology.hasHomePage, Literal("http://oeg.fi.upm.es/", datatype=XSD.string)))
g.add((person.Oscar, ontology.hasColleague, person.Asun))
g.add((person.Asun,  ontology.hasColleague, person.Raul))


for s, p, o in g:
    print(s, p, o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

from rdflib import Namespace, Literal
from rdflib.namespace import XSD


person = Namespace("http://oeg.fi.upm.es/resource/person/")


foaf  = Namespace("http://xmlns.com/foaf/0.1/")
vcard = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")


g.namespace_manager.bind("foaf",      foaf,  override=False)
g.namespace_manager.bind("vcard-rdf", vcard, override=False)


g.add((person.Oscar, foaf.email,   Literal("oscar@example.com", datatype=XSD.string)))
g.add((person.Oscar, vcard.Given,  Literal("Oscar",             datatype=XSD.string)))
g.add((person.Oscar, vcard.Family, Literal("Corcho",            datatype=XSD.string)))


for s, p, o in g.triples((person.Oscar, None, None)):
    print(s, p, o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")