# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
# Do not change the name of the variables
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""
# Visualize the results
result = [] #list of tuples

for allClasses in g.subjects(RDF.type, RDFS.Class): # Recorro todas las clases
    superclass = None # Var aux por si tiene superclase
    for super in g.objects(allClasses, RDFS.subClassOf): # Si tiene atributo subClassOf, entonces tiene superclase
        superclass = super
        result.append((allClasses, superclass))
    if superclass is None:
        result.append((allClasses, None))

for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query = """
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc . }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query,g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []
classes = set([ns.Person]) # variable para guardar las clases, empezando por person
leftVisit = [ns.Person] 
while leftVisit:
  next = leftVisit.pop()
  for subPerson in g.subjects(RDFS.subClassOf, next):
    if subPerson not in classes: # se recorren todas las subclases de person y todas las subclases de las subclases
            classes.add(subPerson)
            leftVisit.append(subPerson)

seenIndiv = set() # set para los individuos ya recorridos para no repetir
for cla in classes: # Ya con todas las clases se muestran los individuos de cada una
    for indiv in g.subjects(RDF.type, cla):
      if indiv not in seenIndiv:
            individuals.append(indiv)
            seenIndiv.add(indiv)
# visualize results
for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query =  """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
SELECT ?ind
WHERE {
  ?ind rdf:type/rdfs:subClassOf* ns:Person.
}
"""

for r in g.query(query):
  print(r.ind)
# Visualize the results

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = """
PREFIX ns: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?type
WHERE {
    ?person ns:knows ns:Rocky .
    ?person rdfs:label ?name .
    ?person rdf:type ?type .
}
"""
# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """
PREFIX : <http://oeg.fi.upm.es/def/people#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?name
WHERE {
  {
    ?person :hasColleague ?c1 .
    ?c1 :ownsPet ?p .
    ?p rdf:type :Animal .
  }
  UNION
  {
    ?person :hasColleague ?c1 .
    ?c1 :hasColleague ?c2 .
    ?c2 :ownsPet ?p .
    ?p rdf:type :Animal .
  }
  ?person rdfs:label ?name .
}
"""


for r in g.query(query):
  print(r.name)
# Visualize the results

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")
