# -*- coding: utf-8 -*-
"""Task06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10h2RSt2mA_AkzgFkWHNbXJPD9ZI-uKZM

**Task 06: Modifying RDF(s)**
"""

#!pip install rdflib
import urllib.request
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

"""Import RDFLib main methods"""

from rdflib import Graph, Namespace, Literal, XSD
from rdflib.namespace import RDF, RDFS
from validation import Report
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
r = Report()

"""Create a new class named Researcher"""

ns = Namespace("http://mydomain.org#")
g.add((ns.Researcher, RDF.type, RDFS.Class))
for s, p, o in g:
  print(s,p,o)

"""**Task 6.0: Create new prefixes for "ontology" and "person" as shown in slide 14 of the Slidedeck 01a.RDF(s)-SPARQL shown in class.**"""

# this task is validated in the next step
ontology = Namespace("http://oeg.fi.upm.es/def/people#")    #clase ontology
person = Namespace("http://oeg.fi.upm.es/resource/person/") #clase person

# BIND
g.namespace_manager.bind('ontology', ontology)
g.namespace_manager.bind('person', person)

"""**TASK 6.1: Reproduce the taxonomy of classes shown in slide 34 in class (all the classes under "Vocabulario", Slidedeck: 01a.RDF(s)-SPARQL). Add labels for each of them as they are in the diagram (exactly) with no language tags. Remember adding the correct datatype (xsd:String) when appropriate**

"""

# TO DO
# CLASSES
g.add((ontology.Person, RDF.type, RDFS.Class))                    # clase Person
g.add((ontology.Professor, RDF.type, RDFS.Class))                 # clase Professor (subclase de Person)
g.add((ontology.AssociateProfessor, RDF.type, RDFS.Class))        # clase AssociateProfessor (subclase de Professor)
g.add((ontology.FullProfessor, RDF.type, RDFS.Class))             # clase FullProfessor (subclase de Professor)
g.add((ontology.InterimAssociateProfessor, RDF.type, RDFS.Class)) # clase InterimAssociateProfessor (subclase de AssociateProfessor)

# SUBCLASSES
g.add((ontology.Professor, RDFS.subClassOf, ontology.Person))                             # Professor (subclase de Person)
g.add((ontology.AssociateProfessor, RDFS.subClassOf, ontology.Professor))                 # AssociateProfessor (subclase de Professor)
g.add((ontology.FullProfessor, RDFS.subClassOf, ontology.Professor))                      # FullProfessor (subclase de Professor)
g.add((ontology.InterimAssociateProfessor, RDFS.subClassOf, ontology.AssociateProfessor)) # InterimAssociateProfessor (subclase de AssociateProfessor)

# LABELS
g.add((ontology.Person, RDFS.label, Literal("Person", datatype=XSD.string)))
g.add((ontology.Professor, RDFS.label, Literal("Professor", datatype=XSD.string)))
g.add((ontology.AssociateProfessor, RDFS.label, Literal("AssociateProfessor", datatype=XSD.string)))
g.add((ontology.FullProfessor, RDFS.label, Literal("FullProfessor", datatype=XSD.string)))
g.add((ontology.InterimAssociateProfessor,RDFS.label, Literal("InterimAssociateProfessor", datatype=XSD.string)))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_01(g)

"""**TASK 6.2: Add the 3 properties shown in slide 36. Add labels for each of them (exactly as they are in the slide, with no language tags), and their corresponding domains and ranges using RDFS. Remember adding the correct datatype (xsd:String) when appropriate. If a property has no range, make it a literal (string)**"""

# TO DO
# CREO PROPIEDADES
g.add((ontology.hasName, RDF.type, RDF.Property))       # hasName
g.add((ontology.hasColleague, RDF.type, RDF.Property))  # hasColleague
g.add((ontology.hasHomePage, RDF.type, RDF.Property))   # hasHomePage

# LABELS
g.add((ontology.hasName, RDFS.label, Literal("hasName", datatype=XSD.string)))            # hasName
g.add((ontology.hasColleague, RDFS.label, Literal("hasColleague", datatype=XSD.string)))  # has Colleague
g.add((ontology.hasHomePage, RDFS.label, Literal("hasHomePage", datatype=XSD.string)))    # hasHomePage

# DOMAIN (quien usa la prop)
g.add((ontology.hasName, RDFS.domain, ontology.Person))             # hasName -> Person
g.add((ontology.hasColleague, RDFS.domain, ontology.Person))        # hasColleague -> Person
g.add((ontology.hasHomePage, RDFS.domain, ontology.FullProfessor))  # hasHomePage -> FullProfessor

# RANGE (valor devuelto)
g.add((ontology.hasName, RDFS.range, RDFS.Literal))            # hasName -> literal
g.add((ontology.hasColleague, RDFS.range, ontology.Person))    # hasColleague -> Person
g.add((ontology.hasHomePage, RDFS.range, RDFS.Literal))        # hasHomePage -> Literal
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_02(g)

"""**TASK 6.3: Create the individuals shown in slide 36 under "Datos". Link them with the same relationships shown in the diagram."**"""

# TO DO
# Le pongo labels a las personas que hay en la slide
g.add((person.Oscar, RDFS.label, Literal("Oscar", datatype=XSD.string)))  # label para Oscar (AssociateProfessor)
g.add((person.Asun,  RDFS.label, Literal("Asun",  datatype=XSD.string)))  # label para Asun (FullProfessor)
g.add((person.Raul,  RDFS.label, Literal("Raul",  datatype=XSD.string)))  # label para Raul (InterimAssociateProfessor)

# PERSONAS
g.add((person.Oscar, RDF.type, ontology.AssociateProfessor))        # Oscar (AssociateProfessor)
g.add((person.Asun, RDF.type, ontology.FullProfessor))              # Asun (FullProfessor)
g.add((person.Raul, RDF.type, ontology.InterimAssociateProfessor))  # Raul (InterimAssociateProfessor)

# RELATIONS: OSCAR
g.add((person.Oscar, ontology.hasColleague, person.Asun))                 # Oscar -> hasColleague -> Asun
g.add((person.Oscar, ontology.hasName, Literal("Óscar Corcho García")))   # Oscar -> hasName -> Oscar Corcho Garcia

# REALTION: ASUN
g.add((person.Asun, ontology.hasColleague, person.Raul))                      # Asun -> hasColleague -> Raul
g.add((person.Asun, ontology.hasHomePage,Literal("http://oeg.fi.upm.es/")))   # Asun -> hasHomepage -> http://oeg.fi.upm.es/
# Visualize the results
for s, p, o in g:
  print(s,p,o)

r.validate_task_06_03(g)

"""**TASK 6.4: Add to the individual person:Oscar the email address, given and family names. Use the properties already included in example 4 to describe Jane and John (https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials/rdf/example4.rdf). Do not import the namespaces, add them manually**

"""

# TO DO
VCARD = Namespace("http://www.w3.org/2001/vcard-rdf/3.0/")  # para nombre y apellidos
foaf = Namespace("http://xmlns.com/foaf/0.1/")              # para email

g.add((person.Oscar, VCARD.Given, Literal("Óscar", datatype=XSD.string)))
g.add((person.Oscar, VCARD.Family, Literal("Corcho García",datatype=XSD.string)))
g.add((person.Oscar, foaf.email, Literal("ocorcho@fi.upm.es",datatype=XSD.string)))
# Visualize the results
for s, p, o in g:
  print(s,p,o)

# Validation. Do not remove
r.validate_task_06_04(g)
r.save_report("_Task_06")